entrypoint: bundle exec rackup -p $PORT
env: flex
runtime: ruby

env_variables:
  SECRET_KEY_BASE: 63077c247615df200d667c77ca65ad4de37ffb523aa03f6b59a9139d82189b9e483e8487994e354dd3723e6115e45c5d3b2a492447cedf721fbc5a7432ff94dd
  MYSQL_USER: luftprosjekt
  MYSQL_PASSWORD: eitheigaip4Ex4es5aideweigu4Oopho
  MYSQL_DATABASE: masteroppgave
  MYSQL_SOCKET_PATH: /cloudsql/masteroppgave-177911:europe-west1:luftprosjekt

health_check:
  enable_health_check: True
  check_interval_sec: 10
  timeout_sec: 4
  unhealthy_threshold: 2
  healthy_threshold: 2

beta_settings:
  cloud_sql_instances: masteroppgave-177911:europe-west1:luftprosjekt
